### ISSUE TITLE
Issue with 14.04

### ISSUE THREAD

**Issue by 2Reeko** [TakkTile/TakkTile-usb#11]
I was using a Takkstrip on 12.04 and groovy a while ago without issue, but now on a machine running 14.04 I keep encountering one of these two error msgs. I'm not sure if it's an issue with 14.04 or with the version of python. Has anyone encountered this or can anyone reproduce this?

```
TakkTile-usb$ sudo python TakkTile.py 
Traceback (most recent call last):
  File "TakkTile.py", line 144, in <module>
    tact = TakkTile()
  File "TakkTile.py", line 49, in __init__
    self.alive = [x+arrayID*50 for x in self.getAlive()]
  File "TakkTile.py", line 58, in getAlive
    bitmap = self.dev.ctrl_transfer(0x40|0x80, 0x5C, 0, 0, 8)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1016, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 875, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 592, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
```

or

```
TakkTile-usb$ sudo python TakkTile.py 
Traceback (most recent call last):
  File "TakkTile.py", line 144, in <module>
    tact = TakkTile()
  File "TakkTile.py", line 49, in __init__
    self.alive = [x+arrayID*50 for x in self.getAlive()]
  File "TakkTile.py", line 58, in getAlive
    bitmap = self.dev.ctrl_transfer(0x40|0x80, 0x5C, 0, 0, 8)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 1016, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 875, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 592, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 75] Overflow
```

**Comment by MHornRobotics** [comment]
Looking for answers myself. I'm experiencing your first error nearly 100% of the time. Did you find a way to fix the issues?

**Comment by cpetersmeier** [comment]
Same here! Did anyone find a way? I am getting the error also nearly 100% of the time.

**Comment by RaduCorcodel** [comment]
I am also getting this error. A way to avoid it (though sometimes it still produces the error) is to execute a `stopSampling()` command before exiting the script.
You can register a callback function using `import atexit` module.
